name: actions

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: install dependencies
        run: npm ci

      - name: setup pages
        id: pages
        uses: actions/configure-pages@v5

      - name: build
        run: npx eleventy --pathprefix="${{ steps.pages.outputs.base_path }}"

      - name: upload
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site
  cd:
    name: deploy
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
